# 编辑 /etc/security/limits.conf，增加如下配置（调达了用户级fd限制）：
# https://www.evernote.com/shard/s375/u/0/sh/25b1b4b8-e55a-43a6-b941-a5c54c81af64/f187da05e0bc1993c73c2987fa95bed8
# 解决 redsocks 自动断开问题
# https://yuerblog.cc/2019/10/23/%E6%96%90%E8%AE%AFn1-%E5%88%A9%E7%94%A8redsocksss%E5%AE%9E%E7%8E%B0%E5%85%A8%E5%B1%80%E7%BF%BB%E5%A2%99/
net.ipv4.tcp_keepalive_time = 5
net.ipv4.tcp_keepalive_probes = 2
net.ipv4.tcp_keepalive_intvl = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
fs.file-max = 1000000
net.core.default_qdisc=fq
##  开启bbr

net.ipv4.tcp_congestion_control=bbr